name: Verificar Render

on:
  schedule:
    - cron: '0 6 * * *'  # 06:00 UTC = 08:00 em Moçambique
  workflow_dispatch:      # permite executar manualmente

jobs:
  check-render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pyppeteer

      - name: Run Puppeteer Script
        run: python check_render.py

  cleanup-runs:
    runs-on: ubuntu-latest

    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 7           # Remove execuções com mais de 7 dias
          keep_minimum_runs: 1    # Mantém apenas 1 execução recente
